runtime: nodejs20

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

# Corrected error handler section
error_handlers:
  - error_code: default
    file: build/index.html