runtime: nodejs20
env_variables:
  NODE_ENV: 'production'
handlers:
  - url: /Images
    static_dir: build/Images
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

error_handlers:
  - error_code: default
    file: build/index.html